### ISSUE TITLE
Rename primary branches to follow best practices

### ISSUE THREAD

**Issue by balbirthomas** [finos/contrib-toolbox#14]
Based on the opinions [expressed by GitHub](https://github.com/github/renaming) and [within the Linux kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb), it is no longer appropriate to use the term "master" in any situations. As such, it can be safely recommended that FINOS remove any uses of the "master" branch and replace it with the new standard naming convention of main for primary branches on each repo.

**Comment by maoo** [comment]
Thanks @balbirthomas ! I actually found https://github.com/finos/community/issues/114 to be the main issue on our end, so I'll close this issue and track progress on the community one. Thanks!
